package com.lightningkite.kotlin.anko.viewcontrollers;

import android.content.res.Resources
import android.view.View
import com.lightningkite.kotlin.Disposable

/**
 * An object that manages a view.
 * They are typically stored statically, ensuring that the view controller's data is retained between view recreations.
 * It should retain no references to the views except between calls to [make] and [unmake].
 * Created by jivie on 6/26/15.
 */
interface ViewController : Disposable {
    /**
     * An empty/dummy view controller.
     */
    object EMPTY : ViewController {
        override fun make(vcContext: VCContext): View = View(vcContext.context)
    }

    /**
     * Makes a view that displays the information within this controller.
     */
    fun make(vcContext: VCContext): View

    /**
     * Called when the view is fully animated in.
     */
    fun animateInComplete(vcContext: VCContext, view: View) {
    }

    /**
     * Called when the view is fully animated in.
     */
    fun animateOutStart(vcContext: VCContext, view: View) {
    }

    /**
     * Clean up a view generated by this view controller.
     */
    fun unmake(view: View) {
    }

    /**
     * Dispose anything that needs to be disposed.  After this is called, you should never use this object again.
     */
    override fun dispose() {
    }

    /**
     * Gets the human-friendly title of this view.  Useful for putting the title on the action bar, if you use one.
     */
    fun getTitle(resources: Resources): String = "Untitled"


    /**
     * Called when back is pressed.
     * Example usage:
     * override fun onBackPressed(backAction:()->Unit){
     *      if(canGoBack) backAction()
     *      else informUserWhy()
     * }
     * @param backAction Execute this function to do the parent's onBackPressed.
     */
    fun onBackPressed(view: View, backAction: () -> Unit) = onBackPressed(backAction)


    /**
     * Called when back is pressed.
     * Example usage:
     * override fun onBackPressed(backAction:()->Unit){
     *      if(canGoBack) backAction()
     *      else informUserWhy()
     * }
     * @deprecated Override the full version instead.
     * @param backAction Execute this function to do the parent's onBackPressed.
     */
    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("Override the full onBackPressed() instead.")
    fun onBackPressed(backAction: () -> Unit) {
        backAction()
    }
}
